### ISSUE TITLE
Using a raspberry pi 3b instead of pico

### ISSUE THREAD

**Issue by Mubbler** [Annex-Engineering/Constellation#7]
Would swapping from a pico to a 3b cause any issues? Dont really want to risk damaging a 3b, but if I were to wire the pi I am using to run klipper using the pinout diagram I shouldnt have issues right?

**Comment by Trails5000** [comment]
a 3b wouldnt be supported to drive a supernova or any other constellation board

**Comment by comradef191** [comment]
Out of curiosity late last year I actually tried something similar to what you proposed here so thought i'd drop some details incase anyone comes looking in future

While it worked, and was more capable of higher speeds than my 16MHz Atmega1280, it was ***horribly*** unstable, I would consistently get "Timer too close" errors and some other... really odd errors, even when running the motors EXTREMELY slow
I've been told this is due to something about the HAL of the Pi not being able to keep up.

A neat idea, but sadly not feasible and far too unreliable.
![image](https://github.com/Annex-Engineering/Constellation/assets/62987296/0f5bdc9b-64f7-4d83-a9ed-d02876ddd86c)


![IMG_20231006_123131](https://github.com/Annex-Engineering/Constellation/assets/62987296/95e6c4dd-5368-4af1-b1e2-dd7fe430dda5)
